INFO  | File run_exp_CCN_Project.py | Line 15    | Writing log file to ./exp/GTS_test_1222_174342/log_exp_1010.txt
INFO  | File run_exp_CCN_Project.py | Line 16    | Exp instance id = GTS_test_1222_174342
ERROR | File run_exp_CCN_Project.py | Line 25    | Traceback (most recent call last):
  File "/Users/juhyeonkim/Dropbox/내 Mac (JuHyeonui-iMac.local)/Documents/GraphStructureLearning/run_exp_CCN_Project.py", line 20, in main
    runner.train()
  File "/Users/juhyeonkim/Dropbox/내 Mac (JuHyeonui-iMac.local)/Documents/GraphStructureLearning/runner/CCN_Project_runner.py", line 142, in train
    loss = self.compute_loss(outputs, angle, data_batch.y, self.loss_ratio)
  File "/Users/juhyeonkim/Dropbox/내 Mac (JuHyeonui-iMac.local)/Documents/GraphStructureLearning/runner/CCN_Project_runner.py", line 114, in compute_loss
    classification_cost = self.CE_loss(class_prediction.view((1,8)), target[3,0].view((1,1)))
  File "/opt/anaconda3/envs/GraphStructureLearning/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/anaconda3/envs/GraphStructureLearning/lib/python3.9/site-packages/torch/nn/modules/loss.py", line 1150, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/opt/anaconda3/envs/GraphStructureLearning/lib/python3.9/site-packages/torch/nn/functional.py", line 2846, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: 0D or 1D target tensor expected, multi-target not supported

